[build]
  command = "CI= npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "cors", "dotenv"]
  node_bundler = "esbuild"
  included_files = ["Routes/", "public/"]


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

